export const recipes = [
  {
    id: "1",
    title: "Vegetable Stir Fry",
    image: "https://images.themodernproper.com/production/posts/VegetableStirFry_9.jpg?w=1200&h=1200&q=60&fm=jpg&fit=crop&dm=1703377301&s=79d95f7318643d92c30863f226d5eb8e",
    author: "Jamie Oliver",
    time: "30 minutes",
    difficulty: "Easy",
    categories: ["Vegetarian", "Dinner", "Healthy"],
    likes: 245,
  },
  {
    id: "2",
    title: "Chicken Tikka Masala",
    image: "https://www.seriouseats.com/thmb/DbQHUK2yNCALBnZE-H1M2AKLkok=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/chicken-tikka-masala-for-the-grill-recipe-hero-2_1-cb493f49e30140efbffec162d5f2d1d7.JPG",
    author: "Gordon Ramsay",
    time: "45 minutes",
    difficulty: "Medium",
    categories: ["Non-Vegetarian", "Dinner", "Indian"],
    likes: 189,
  },
  {
    id: "3",
    title: "Avocado Toast",
    image: "https://www.eatingwell.com/thmb/PM3UlLhM0VbE6dcq9ZFwCnMyWHI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/EatingWell-April-Avocado-Toast-Directions-04-5b5b86524a3d4b35ac4c57863f6095dc.jpg",
    author: "Nigella Lawson",
    time: "10 minutes",
    difficulty: "Easy",
    categories: ["Vegetarian", "Breakfast", "Quick"],
    likes: 156,
  },
  {
    id: "4",
    title: "Chocolate Chip Cookies",
    image: "http://handletheheat.com/wp-content/uploads/2020/10/BAKERY-STYLE-CHOCOLATE-CHIP-COOKIES-9-637x637-1.jpg",
    author: "Mary Berry",
    time: "25 minutes",
    difficulty: "Easy",
    categories: ["Dessert", "Baking", "Snack"],
    likes: 312,
  },
  {
    id: "5",
    title: "Beef Burger",
    image: "/placeholder.svg?height=450&width=800",
    author: "Bobby Flay",
    time: "20 minutes",
    difficulty: "Easy",
    categories: ["Non-Vegetarian", "Lunch", "American"],
    likes: 178,
  },
  {
    id: "6",
    title: "Mushroom Risotto",
    image: "/placeholder.svg?height=450&width=800",
    author: "Antonio Carluccio",
    time: "40 minutes",
    difficulty: "Medium",
    categories: ["Vegetarian", "Dinner", "Italian"],
    likes: 145,
  },
  {
    id: "7",
    title: "Salmon with Asparagus",
    image: "/placeholder.svg?height=450&width=800",
    author: "Rick Stein",
    time: "25 minutes",
    difficulty: "Medium",
    categories: ["Non-Vegetarian", "Dinner", "Seafood"],
    likes: 132,
  },
  {
    id: "8",
    title: "Banana Bread",
    image: "/placeholder.svg?height=450&width=800",
    author: "Delia Smith",
    time: "60 minutes",
    difficulty: "Easy",
    categories: ["Dessert", "Baking", "Breakfast"],
    likes: 267,
  },
  
]
